### ISSUE TITLE
R-32 Que desde Conteo de Victimizaciones Individuales haya un botón Mostrar Mapa que abra en otra ventana el prototipo de mapa analizado y mejorado [8]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_somosdefensores#32]

**Comment by vtamara** [comment]
![SIADDHH 2-1a1 6-10-2021 9-13-09 a- m-](https://user-images.githubusercontent.com/701221/136220286-4261f5a1-e91e-45c6-9b1b-46f5b377d491.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-10-07 15-46-34](https://user-images.githubusercontent.com/10052756/136459921-1c75c306-80a3-4a5d-a59e-374a73ad7dec.png)
![Captura de pantalla de 2021-10-07 15-47-10](https://user-images.githubusercontent.com/10052756/136459946-76cece5a-b605-472b-8b05-7071243512cd.png)

**Comment by pmartinez5** [comment]
En el momento de hacer la prueba de usuario el dia 15 de octubre no me sale el boton de mapa
![screenshoteasy (1)](https://user-images.githubusercontent.com/61369119/137571793-5f426d7c-6eea-4099-8345-1a4b9b662f32.png)

**Comment by pmartinez5** [comment]
[
![FireShot Capture 120 - SIADDHH 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/139793094-58de1923-e236-490f-9985-9ec888aea9a2.png)
](url)
