### ISSUE TITLE
F-34 En formulario de caso, anexo, que se vea "Tipo de anexo" en lugar de "Tipoanexo", (2) el botón de eliminar no ocupe todo el ancho, (3) que tras guardar y volver a editar no quede un espacio en blanco entre el anexo y botón de Guardar, (4) que desde la pestaña anexo se pueda pasar de maner normal a las pestañas que siguen (ahora no se puede queda el contenido de la otra pestaña en la de anexos). [0,2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_somosdefensores#34]
![SIADDHH 2-1a1 6-10-2021 2-27-52 p- m-](https://user-images.githubusercontent.com/701221/136270548-382875a9-b5a5-444a-966e-cc507c92b557.png)

**Comment by pmartinez5** [comment]
[
![FireShot Capture 114 - SIADDHH 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/139779218-ed9028d1-9873-4424-9c0c-c277ccd59859.png)
](url)
PU-F-34

**Comment by pmartinez5** [comment]
[
![Uploading FireShot Capture 116 - SIADDHH 2.1a1 - rbd.nocheyniebla.org.png…]()
](url)
