### ISSUE TITLE
R-51 Desde el mapa, nuevo botón Descargar CSV que descargue casos presentados en el mapa [3]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_somosdefensores#51]

**Comment by pmartinez5** [comment]
[
![FireShot Capture 118 - SIADDHH 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/139784857-1e452c47-c52d-439a-bcd5-fa8aad30e84b.png)
](url)
PU-R-51 probar R-51
